import { Layout, NextPageWithLayout } from '@/components/Theme'
import Head from 'next/head'
import Link from 'next/link'

const Modal: NextPageWithLayout = () => (
  <>
    <Head>
      <title>Modal</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1>This is how the Overlay looks like</h1>
      <Link href="/">Check out the Main too!</Link>
      <br />
      <Link href="/overlays/2">Maybe another overaly?</Link>
      <br />
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce et turpis
        sed augue interdum consequat. Orci varius natoque penatibus et magnis
        dis parturient montes, nascetur ridiculus mus. Vivamus sit amet
        scelerisque dui. Pellentesque congue massa vel gravida mollis. Nulla
        convallis, ex vitae egestas ornare, mi tellus lacinia libero, nec
        interdum tellus eros sit amet ipsum. Integer massa enim, bibendum nec
        ornare et, ornare eu turpis. Etiam non justo eu purus ullamcorper
        ullamcorper et nec magna. In euismod orci pretium tellus cursus, sit
        amet convallis massa suscipit. Morbi aliquet risus in pulvinar
        consectetur. Quisque ultricies orci in condimentum condimentum. Mauris
        id est pharetra, dignissim magna ut, commodo ante.
      </p>
      <p>
        Pellentesque ullamcorper feugiat nulla, et molestie augue dignissim
        tincidunt. Ut tempus tellus velit, quis dapibus metus auctor vel. Sed
        elementum nisi placerat nulla semper, eu pretium felis faucibus. Nulla
        non arcu mattis, consectetur massa ut, blandit velit. Aliquam at ante
        quis mauris euismod hendrerit malesuada fringilla dui. Vivamus faucibus
        consectetur nibh interdum vulputate. Donec non nulla semper,
        pellentesque purus eget, mollis nisl.
      </p>
      <p>
        Donec facilisis tempor bibendum. Morbi lectus diam, fringilla et sapien
        at, ornare laoreet tortor. Donec venenatis elit sit amet velit accumsan
        gravida. Praesent quis magna libero. Proin dignissim ante eget dignissim
        feugiat. Curabitur lobortis nisi magna, sit amet tincidunt libero
        convallis non. Nunc porta, nisl eu tristique porta, arcu dolor venenatis
        turpis, sed cursus ligula tortor in purus. Nulla fermentum sed nunc nec
        luctus.
      </p>
      <p>
        Mauris diam lectus, elementum ac consequat et, euismod semper nibh.
        Vestibulum efficitur consectetur mi non bibendum. Pellentesque at
        ullamcorper risus, sit amet malesuada massa. Praesent dictum odio sed
        ullamcorper dictum. Donec ultricies sem dui, non suscipit arcu vehicula
        a. Phasellus at condimentum arcu. Etiam elementum pellentesque arcu vel
        facilisis.
      </p>
      <p>
        Pellentesque ornare auctor pharetra. Aliquam et mi faucibus, molestie
        velit ut, malesuada quam. Sed nec nisi eleifend, vestibulum justo vel,
        pulvinar libero. Quisque pellentesque lacinia nibh in pulvinar. Morbi
        ultrices at turpis at varius. Morbi dapibus dolor eu lectus placerat
        iaculis. Ut a nibh condimentum, iaculis justo vitae, tempor quam.
      </p>
      <p>
        Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
        inceptos himenaeos. Sed pharetra scelerisque sem, at aliquam massa
        gravida ut. Morbi mi nulla, consectetur eget lacus at, molestie lobortis
        sapien. Mauris vel purus ac mi posuere rhoncus. Nulla neque justo,
        ullamcorper a mi ac, tempus tincidunt magna. Quisque vitae ultrices
        arcu. Vestibulum venenatis elementum nisi, ut vehicula tortor accumsan
        et. Etiam ac turpis in est semper facilisis. Maecenas elementum purus
        vitae dui efficitur gravida. Donec eget faucibus ante. In congue ornare
        sem sed molestie. Suspendisse malesuada leo sit amet ligula hendrerit
        mollis ut a magna. Proin nec pellentesque nibh, vel vehicula leo. In eu
        semper mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Morbi iaculis finibus suscipit.
      </p>
      <p>
        Aenean ac lobortis tortor. Suspendisse potenti. Proin dictum aliquet
        mauris, nec placerat dolor facilisis quis. Donec et dui quis nisl
        pharetra faucibus. Nulla quis vehicula nulla. Fusce venenatis massa non
        posuere mattis. In suscipit laoreet aliquam. Nulla tristique commodo
        est, nec vulputate tortor pretium a. Suspendisse hendrerit orci a felis
        iaculis fermentum. Proin malesuada magna vitae neque fermentum viverra.
        Curabitur sagittis vel dolor nec tincidunt. Curabitur nisi purus,
        vestibulum vel pellentesque ut, venenatis et augue. Nullam ac sapien et
        nisl varius gravida placerat vel tortor. Phasellus a nisi eu nunc
        ullamcorper ultricies. Proin varius consequat lacus, eu tristique arcu
        blandit in.
      </p>
      <p>
        Ut tempor eros quis interdum dignissim. Etiam vehicula augue quis mattis
        consectetur. Duis hendrerit enim lectus, ut tempus sem feugiat eu.
        Aliquam erat volutpat. In odio nunc, iaculis ac ornare in, volutpat ut
        leo. Morbi vehicula at ex vitae ultricies. Sed vestibulum tempus
        vulputate. Aliquam tincidunt tempor eros sit amet laoreet. Proin ut enim
        neque. Nulla nec dolor sit amet enim congue sollicitudin. Praesent at
        ante id quam sagittis sollicitudin. Fusce finibus erat sed dui
        imperdiet, in tincidunt orci cursus. Quisque elementum consectetur enim
        vel semper. Integer sed erat fringilla, faucibus felis maximus,
        vulputate est. Sed sit amet felis ac eros aliquet laoreet non sit amet
        mauris. Mauris posuere lorem sit amet eros consequat, sit amet faucibus
        mi finibus.
      </p>
      <p>
        Quisque condimentum massa purus, vitae placerat neque sollicitudin sed.
        Praesent tincidunt quis mauris sed varius. Integer ac dapibus elit,
        vitae commodo elit. Class aptent taciti sociosqu ad litora torquent per
        conubia nostra, per inceptos himenaeos. Nullam interdum libero eu tellus
        pellentesque, ultrices tempus sem pulvinar. Sed eu suscipit ante, eu
        elementum quam. Praesent eu orci eu eros consequat venenatis. Phasellus
        quis fermentum est.
      </p>
      <p>
        Donec id condimentum risus. Sed leo tellus, condimentum non iaculis a,
        scelerisque non libero. Aliquam aliquam eros dui, in pretium turpis
        commodo eget. Donec a dapibus sapien. Nulla maximus nibh sed lobortis
        tincidunt. Curabitur purus nisi, tempor id dolor vel, pretium tempus
        odio. Cras et vestibulum ipsum. Sed congue convallis ex eu fringilla.
        Maecenas id nisi eleifend, tempor sem ullamcorper, faucibus est.
        Suspendisse vitae ullamcorper est. In justo dui, condimentum non quam
        vel, aliquam lobortis diam. Nam lacus ligula, varius a lorem non,
        bibendum pellentesque urna. Vestibulum et turpis neque. Nullam gravida
        sodales maximus. In vel porttitor ligula, at elementum sapien. Vivamus
        elit purus, fermentum sed auctor vel, elementum eu nunc.
      </p>
      <p>
        Nam massa turpis, auctor sit amet fringilla auctor, pharetra sit amet
        lacus. In sit amet facilisis lacus, vel ultricies arcu. Cras id mi ut
        magna dignissim dictum nec in odio. Phasellus eget tortor eu tellus
        porttitor fermentum. Nulla at ipsum nec mauris commodo aliquam. Nullam
        condimentum rutrum blandit. Lorem ipsum dolor sit amet, consectetur
        adipiscing elit.
      </p>
      <p>
        Vivamus mauris sem, elementum posuere neque id, bibendum hendrerit odio.
        Nunc risus quam, dictum volutpat consectetur sed, vulputate eget nibh.
        Cras eu nibh ligula. Morbi consectetur facilisis purus, et mollis eros
        pulvinar non. Cras lacinia felis nec urna tincidunt feugiat. Proin nec
        blandit risus, at pulvinar ligula. Fusce quis ultrices est. Etiam
        malesuada vel orci at scelerisque. Nulla quis purus ut velit hendrerit
        tincidunt. Vivamus nec scelerisque justo, fermentum dignissim dui. Fusce
        vel lorem neque. Donec congue ac mi vel porta.
      </p>
    </main>
  </>
)

Modal.layout = Layout.Overlay

export default Modal
